/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.Controller;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {
 String user="";
    DefaultListModel modeloLista = new DefaultListModel();
   
 
//    Controller ctrl =new Controller();

    /**
     * Creates new form Menu
     */
    public Menu() {
   
        initComponents();
        
//      ctrl.cargarTablaFuncYAvtivos();
      
      
        jList1.setModel(modeloLista);
        this.setLocationRelativeTo(null);
    }

    public void tabla() {
        Controller ctrl = new Controller();
        ctrl.cargarTablaFuncYAvtivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalir = new javax.swing.JPanel();
        jlMinimizar = new javax.swing.JLabel();
        jlSalir = new javax.swing.JLabel();
        jPIngresar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFunActi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBValidar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jBAgregar = new javax.swing.JButton();
        jBQuitar = new javax.swing.JButton();
        jlEtiqueta = new javax.swing.JLabel();
        jpValidar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPSalir.setBackground(new java.awt.Color(255, 255, 255));
        jPSalir.setForeground(new java.awt.Color(255, 255, 255));
        jPSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
        });
        jPSalir.add(jlMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
        });
        jPSalir.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        getContentPane().add(jPSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 30));

        jPIngresar.setBackground(new java.awt.Color(255, 255, 255));
        jPIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFunActi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTFunActi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFunActiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFunActiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTFunActi);

        jPIngresar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 360, 170));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setText("FUNCIONARIOS Y ACTIVOS");
        jPIngresar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jBValidar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBValidar.setText("Validar");
        jBValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValidarActionPerformed(evt);
            }
        });
        jPIngresar.add(jBValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jScrollPane2.setViewportView(jList1);

        jPIngresar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 90, 170));

        jBAgregar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBAgregar.setText(">>");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPIngresar.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        jBQuitar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBQuitar.setText("<<");
        jBQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitarActionPerformed(evt);
            }
        });
        jPIngresar.add(jBQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));
        jPIngresar.add(jlEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, 30));

        getContentPane().add(jPIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 550));

        jpValidar.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla);

        jTextField1.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setText("PROCESO DE VALIDACION.");

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del proceso : ");

        jBRegresar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpValidarLayout = new javax.swing.GroupLayout(jpValidar);
        jpValidar.setLayout(jpValidarLayout);
        jpValidarLayout.setHorizontalGroup(
            jpValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2))
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3))
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBRegresar)
                .addGap(293, 293, 293)
                .addComponent(jBGuardar))
        );
        jpValidarLayout.setVerticalGroup(
            jpValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpValidarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(jpValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBRegresar)
                    .addComponent(jBGuardar)))
        );

        getContentPane().add(jpValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 560, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public Object usuarios(){
    Object lista =modeloLista.getListDataListeners();
    return lista;
}


    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "SALIR", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        this.setState(Principal.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jBValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValidarActionPerformed
        Controller ctrl = new Controller();
//        ctrl.cargarTablaValidar();
      jpValidar.setVisible(true);
//      jPIngresar.setVisible(false);
//        ctrl.cargarValidador();
        
    
        this.dispose();
        

    }//GEN-LAST:event_jBValidarActionPerformed

    private void jTFunActiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFunActiMouseClicked
        int fila = jTFunActi.getSelectedRow();
        String nom = jTFunActi.getValueAt(fila, 2).toString();
        user = jTFunActi.getValueAt(fila,1).toString();
      jlEtiqueta.setText(nom);
    }//GEN-LAST:event_jTFunActiMouseClicked

 
    
    
    private void jTFunActiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFunActiMousePressed


    }//GEN-LAST:event_jTFunActiMousePressed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String elemto=user;
        modeloLista.addElement(elemto);
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitarActionPerformed
     int ind=jList1.getSelectedIndex();
     modeloLista.remove(ind);
    }//GEN-LAST:event_jBQuitarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        //        int fila= tabla.getSelectedRow();
        //            dato= tabla.getValueAt(fila, 0).toString();
        //           etiqueta.setText(dato);
        //          hola.addElement(dato);

    }//GEN-LAST:event_tablaMouseClicked

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        Menu v3= new Menu();
        Controller ctrl=new Controller();
        ctrl.cargarTablaFuncYAvtivos();
        Principal v1= new Principal();
        v1.setVisible(false);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

    }//GEN-LAST:event_jBGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBQuitar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JButton jBValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPIngresar;
    private javax.swing.JPanel jPSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTFunActi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlEtiqueta;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JPanel jpValidar;
    public static javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<Web.FunActivos> verFunyActivos() {
        Web.NewWebService_Service service = new Web.NewWebService_Service();
        Web.NewWebService port = service.getNewWebServicePort();
        return port.verFunyActivos();
    }
}
