/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import AppPackage.AnimationClass;
import Controlador.Controller;
import Objetos.Rol;
import Pruebas.Controlador;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jPMenu2.setVisible(false);
        jPAgendar.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public void internet() {
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void youtube() {
        try {
            Desktop.getDesktop().browse(URI.create("https://youtu.be/j4D1zHPBBQY"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalir = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();
        jlMinimizar = new javax.swing.JLabel();
        jPIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlMenu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jlMusica = new javax.swing.JLabel();
        jlCalculadora = new javax.swing.JLabel();
        jlInternet = new javax.swing.JLabel();
        jPMenu1 = new javax.swing.JPanel();
        jPMenu2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jBagendar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbSalir1 = new javax.swing.JButton();
        jPAgendar = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUsuario1 = new javax.swing.JTable();
        btUsU1 = new javax.swing.JButton();
        btUsD1 = new javax.swing.JButton();
        txUsS = new javax.swing.JTextField();
        btRlUPS1 = new javax.swing.JButton();
        btRlUPN1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txUsCed = new javax.swing.JTextField();
        txUsId = new javax.swing.JTextField();
        btUsG = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txUsNom = new javax.swing.JTextField();
        txUsApe = new javax.swing.JTextField();
        txUsCor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txUsTel = new javax.swing.JTextField();
        txUsCon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txUsDir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPSalir.setBackground(new java.awt.Color(255, 255, 255));
        jPSalir.setForeground(new java.awt.Color(255, 255, 255));
        jPSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
        });
        jPSalir.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 30, 30));

        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
        });
        jPSalir.add(jlMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, 30));

        getContentPane().add(jPSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 40));

        jPIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jPIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jPIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 111, 82));
        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 111, 82));
        jLabel1.setText("CONTRASEÑA:");
        jPIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel2.setBackground(new java.awt.Color(238, 111, 82));
        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 111, 82));
        jLabel2.setText("USUARIO:");
        jPIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_96px_2.png"))); // NOI18N
        jPIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 100, 110));

        jtxtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtUser.setForeground(new java.awt.Color(153, 153, 153));
        jtxtUser.setText("Ingrese su usuario.");
        jtxtUser.setBorder(null);
        jtxtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtUserMouseClicked(evt);
            }
        });
        jtxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserActionPerformed(evt);
            }
        });
        jPIngreso.add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 170, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 30));

        jlMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Menu_32px.png"))); // NOI18N
        jlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMenuMouseClicked(evt);
            }
        });
        jPIngreso.add(jlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_customer_32px_1.png"))); // NOI18N
        jPIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Key_32px.png"))); // NOI18N
        jPIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jtxtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtPass.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPass.setText("jPassword53,1d2");
        jtxtPass.setBorder(null);
        jtxtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtPassMouseClicked(evt);
            }
        });
        jtxtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPassActionPerformed(evt);
            }
        });
        jPIngreso.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 160, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 461, 150, 50));

        jlMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Musical_Notes_32px.png"))); // NOI18N
        jlMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMusicaMouseClicked(evt);
            }
        });
        jPIngreso.add(jlMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 160, 40, 40));

        jlCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Calculator_32px.png"))); // NOI18N
        jlCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCalculadoraMouseClicked(evt);
            }
        });
        jPIngreso.add(jlCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 110, 40, 40));

        jlInternet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Globe_32px.png"))); // NOI18N
        jlInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlInternetMouseClicked(evt);
            }
        });
        jPIngreso.add(jlInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 40, 40));

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jPMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jPMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 760, 530));

        jPMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jPMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jPMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 99, 71));
        jButton4.setForeground(new java.awt.Color(255, 99, 71));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Clock_96px.png"))); // NOI18N
        jButton4.setText("HORARIOS");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPMenu2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 99, 71));
        jButton5.setForeground(new java.awt.Color(255, 99, 71));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Google_Drive_96px.png"))); // NOI18N
        jButton5.setText("RUTAS");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPMenu2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 99, 71));
        jButton3.setForeground(new java.awt.Color(255, 99, 71));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Idea_96px.png"))); // NOI18N
        jButton3.setText("AGENDAR");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPMenu2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jButton9.setBackground(new java.awt.Color(255, 99, 71));
        jButton9.setForeground(new java.awt.Color(255, 99, 71));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Maintenance_96px.png"))); // NOI18N
        jButton9.setText("AGENDAR");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPMenu2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, 100));

        jBagendar.setBackground(new java.awt.Color(255, 99, 71));
        jBagendar.setForeground(new java.awt.Color(255, 99, 71));
        jBagendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Today_96px.png"))); // NOI18N
        jBagendar.setText("AGENDAR");
        jBagendar.setBorder(null);
        jBagendar.setBorderPainted(false);
        jBagendar.setContentAreaFilled(false);
        jBagendar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBagendarMouseMoved(evt);
            }
        });
        jBagendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBagendarMouseExited(evt);
            }
        });
        jBagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagendarActionPerformed(evt);
            }
        });
        jPMenu2.add(jBagendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 160));

        jButton6.setBackground(new java.awt.Color(255, 99, 71));
        jButton6.setForeground(new java.awt.Color(255, 99, 71));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Handshake_96px.png"))); // NOI18N
        jButton6.setText("COOPERATIVA");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPMenu2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jbSalir1.setText("<--  SALIR");
        jbSalir1.setBorderPainted(false);
        jbSalir1.setContentAreaFilled(false);
        jbSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalir1ActionPerformed(evt);
            }
        });
        jPMenu2.add(jbSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, -1, -1));

        getContentPane().add(jPMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 530));

        jPAgendar.setBackground(new java.awt.Color(255, 255, 255));
        jPAgendar.setForeground(new java.awt.Color(255, 255, 255));
        jPAgendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jtUsuario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtUsuario1);

        btUsU1.setText("Editar");
        btUsU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsU1ActionPerformed(evt);
            }
        });

        btUsD1.setText("Eliminar");
        btUsD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsD1ActionPerformed(evt);
            }
        });

        btRlUPS1.setText("S");
        btRlUPS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRlUPS1ActionPerformed(evt);
            }
        });

        btRlUPN1.setText("N");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btUsU1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUsD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRlUPS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btRlUPN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txUsS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btUsU1)
                        .addComponent(btUsD1)
                        .addComponent(txUsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btRlUPS1)
                    .addComponent(btRlUPN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPAgendar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 910, 220));

        jLabel23.setText("Id");
        jPAgendar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel24.setText("Cedula");
        jPAgendar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        jPAgendar.add(txUsCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, -1));
        jPAgendar.add(txUsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 20, -1));

        btUsG.setText("Guardar");
        btUsG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsGActionPerformed(evt);
            }
        });
        jPAgendar.add(btUsG, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        jLabel25.setText("Nombre");
        jPAgendar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel26.setText("Apellido");
        jPAgendar.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));
        jPAgendar.add(txUsNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, -1));
        jPAgendar.add(txUsApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 140, -1));
        jPAgendar.add(txUsCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 130, -1));

        jLabel7.setText("Correo");
        jPAgendar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        jLabel8.setText("Telefono");
        jPAgendar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));
        jPAgendar.add(txUsTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 110, -1));
        jPAgendar.add(txUsCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));

        jLabel9.setText("Direccion");
        jPAgendar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel10.setText("Contraseña");
        jPAgendar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jPAgendar.add(txUsDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 330, -1));

        jLabel11.setText("Rol");
        jPAgendar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });
        jPAgendar.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 120, -1));

        jbSalir.setText("REGRESAR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPAgendar.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Buscar...");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jPAgendar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 230, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_32px_2.png"))); // NOI18N
        jPAgendar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        getContentPane().add(jPAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1050, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserActionPerformed

    private void jtxtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPassActionPerformed

    private void jlMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMenuMouseClicked
        AnimationClass internet = new AnimationClass();
////        //(posActua,Adonde,veloc,veloc,nombre_objeto)
        internet.jLabelXRight(-40, 10, 10, 5, jlInternet);
        //----->mostrar
        //y
        //<-----ocultar
        AnimationClass internet2 = new AnimationClass();
        internet2.jLabelXLeft(10, -40, 10, 5, jlInternet);

        AnimationClass cal = new AnimationClass();
        cal.jLabelXRight(-40, 10, 10, 5, jlCalculadora);
        AnimationClass calc2 = new AnimationClass();
        calc2.jLabelXLeft(10, -40, 10, 5, jlCalculadora);
        AnimationClass music = new AnimationClass();
        music.jLabelXRight(-40, 10, 10, 5, jlMusica);
        AnimationClass music2 = new AnimationClass();
        music2.jLabelXLeft(10, -40, 10, 5, jlMusica);
    }//GEN-LAST:event_jlMenuMouseClicked

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        this.setState(Principal.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "SALIR", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlInternetMouseClicked
        internet();
    }//GEN-LAST:event_jlInternetMouseClicked

    private void jlCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCalculadoraMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jlCalculadoraMouseClicked

    private void jlMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMusicaMouseClicked
        youtube();
    }//GEN-LAST:event_jlMusicaMouseClicked

    private void jBagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagendarActionPerformed
        this.jPAgendar.setVisible(true);
        jPIngreso.setVisible(false);
        jPMenu2.setVisible(false);
        jPMenu1.setVisible(false);
    }//GEN-LAST:event_jBagendarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jBagendarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBagendarMouseMoved
        jBagendar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 111, 82)));
    }//GEN-LAST:event_jBagendarMouseMoved

    private void jBagendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBagendarMouseExited
          jBagendar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jBagendarMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Controller control=new Controller();
       Boolean resp= control.login();
       if (resp==true){
           jPIngreso.setVisible(false);
           jPMenu1.setVisible(false);
           jPMenu2.setVisible(true);
           JOptionPane.showMessageDialog(null, "Bienvenido");
       }else{
          JOptionPane.showMessageDialog(null, "Datos incorrectos"); 
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUserMouseClicked
        jtxtUser.setText("");
    }//GEN-LAST:event_jtxtUserMouseClicked

    private void jtxtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPassMouseClicked
        jtxtPass.setText("");
    }//GEN-LAST:event_jtxtPassMouseClicked

    private void btUsD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsD1ActionPerformed
        Controlador ct= new Controlador();
        int id= Integer.parseInt(this.jtUsuario.getValueAt(this.jtUsuario.getSelectedRow(), 8).toString());
        ct.eliminarUsuario(id);
      
    }//GEN-LAST:event_btUsD1ActionPerformed

    private void btRlUPS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRlUPS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRlUPS1ActionPerformed

    private void btUsGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsGActionPerformed

        // paso 5 cargar desde el controlador el metodo para crear el objeto en cuestion
        Controlador con = new Controlador();
        con.crearUsuario(this.txUsCed.getText(), this.txUsNom.getText(),
            this.txUsApe.getText(), this.txUsTel.getText(),
            this.txUsCor.getText(), this.txUsDir.getText(),
            this.txUsCon.getText(),
            this.cbRol.getItemAt(this.cbRol.getSelectedIndex()));

    

    }//GEN-LAST:event_btUsGActionPerformed

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed

    }//GEN-LAST:event_cbRolActionPerformed

    private void btUsU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsU1ActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
         jPIngreso.setVisible(false);
           jPMenu1.setVisible(false);
           jPAgendar.setVisible(false);
           jPMenu2.setVisible(true);
        

    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalir1ActionPerformed
         jPIngreso.setVisible(true);
           jPMenu1.setVisible(true);
           jPMenu2.setVisible(false);
           jtxtPass.setText("");
           jtxtUser.setText("");
    }//GEN-LAST:event_jbSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRlUPN1;
    private javax.swing.JButton btRlUPS1;
    private javax.swing.JButton btUsD;
    private javax.swing.JButton btUsD1;
    private javax.swing.JButton btUsG;
    private javax.swing.JButton btUsU;
    private javax.swing.JButton btUsU1;
    private javax.swing.JComboBox<Rol> cbRol;
    private javax.swing.JButton jBagendar;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAgendar;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPMenu1;
    private javax.swing.JPanel jPMenu2;
    private javax.swing.JPanel jPSalir;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSalir1;
    private javax.swing.JLabel jlCalculadora;
    private javax.swing.JLabel jlInternet;
    private javax.swing.JLabel jlMenu;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlMusica;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JTable jtUsuario1;
    public static javax.swing.JPasswordField jtxtPass;
    public static javax.swing.JTextField jtxtUser;
    private javax.swing.JTextField txUsApe;
    private javax.swing.JTextField txUsCed;
    private javax.swing.JTextField txUsCon;
    private javax.swing.JTextField txUsCor;
    private javax.swing.JTextField txUsDir;
    private javax.swing.JTextField txUsId;
    private javax.swing.JTextField txUsNom;
    private javax.swing.JTextField txUsS;
    private javax.swing.JTextField txUsTel;
    // End of variables declaration//GEN-END:variables
}
