/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.Controller;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Pvalidar extends javax.swing.JFrame {
//
//    String user = "";
//    String dato = "";
//    DefaultListModel modeloLista = new DefaultListModel();
//   Controller con = new Controller();

    /**
     * Creates new form NewJFrame
     */
    public Pvalidar() {
        initComponents();

        this.setLocationRelativeTo(null);
        jpFunyActivos.setVisible(true);
        jpActivos.setVisible(false);
//       con.cargarTablaValidar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPSalir = new javax.swing.JPanel();
        jlMinimizar = new javax.swing.JLabel();
        jlSalir = new javax.swing.JLabel();
        jpActivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablajp = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpFunyActivos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFunActijp = new javax.swing.JTable();
        jBQuitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jBValidar = new javax.swing.JButton();
        jlEtiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPSalir.setBackground(new java.awt.Color(255, 255, 255));
        jPSalir.setForeground(new java.awt.Color(255, 255, 255));
        jPSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jlMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizarMouseClicked(evt);
            }
        });
        jPSalir.add(jlMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
        });
        jPSalir.add(jlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        getContentPane().add(jPSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        jpActivos.setBackground(new java.awt.Color(255, 255, 255));
        jpActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablajp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablajp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablajpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablajp);

        jpActivos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 375, 109));

        jTextField1.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jpActivos.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, -1));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setText("PROCESO DE VALIDACION.");
        jpActivos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del proceso : ");
        jpActivos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jBRegresar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });
        jpActivos.add(jBRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, 40));

        jButton2.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpActivos.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, 40));

        getContentPane().add(jpActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 560, 530));

        jpFunyActivos.setBackground(new java.awt.Color(255, 255, 255));
        jpFunyActivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel3.setText("FUNCIONARIOS Y ACTIVOS");
        jpFunyActivos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 41, -1, -1));

        jBAgregar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBAgregar.setText(">>");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jpFunyActivos.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 191, 50, -1));

        jTFunActijp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTFunActijp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFunActijpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFunActijpMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTFunActijp);

        jpFunyActivos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 170));

        jBQuitar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBQuitar.setText("<<");
        jBQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitarActionPerformed(evt);
            }
        });
        jpFunyActivos.add(jBQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 191, -1, -1));

        jScrollPane3.setViewportView(jList1);

        jpFunyActivos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 231, 90, 170));

        jBValidar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jBValidar.setText("Validar");
        jBValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValidarActionPerformed(evt);
            }
        });
        jpFunyActivos.add(jBValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jlEtiqueta.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jpFunyActivos.add(jlEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 127, 30));

        getContentPane().add(jpFunyActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 560, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablajpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablajpMouseClicked
//        int fila= tabla.getSelectedRow();
//            dato= tabla.getValueAt(fila, 0).toString();
//           etiqueta.setText(dato);
//          hola.addElement(dato);

    }//GEN-LAST:event_tablajpMouseClicked

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed

        Controller ctrl = new Controller();
        ctrl.cargarTablaFuncYAvtivos();
        jpFunyActivos.setVisible(true);
        jpActivos.setVisible(false);


    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizarMouseClicked
        this.setState(Pvalidar.ICONIFIED);
    }//GEN-LAST:event_jlMinimizarMouseClicked

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "SALIR", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed

    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jTFunActijpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFunActijpMouseClicked
//        int fila = jTFunActi.getSelectedRow();
//        String nom = jTFunActi.getValueAt(fila, 2).toString();
//        user = jTFunActi.getValueAt(fila, 1).toString();
//        jlEtiqueta.setText(nom);
    }//GEN-LAST:event_jTFunActijpMouseClicked

    private void jTFunActijpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFunActijpMousePressed

    }//GEN-LAST:event_jTFunActijpMousePressed

    private void jBQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitarActionPerformed
//        int ind = jList1.getSelectedIndex();
//        modeloLista.remove(ind);
    }//GEN-LAST:event_jBQuitarActionPerformed

    private void jBValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValidarActionPerformed
//        Controller ctrl = new Controller();
//        jpActivos.setVisible(true);
//        jpFunyActivos.setVisible(false);


    }//GEN-LAST:event_jBValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pvalidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pvalidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pvalidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pvalidar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pvalidar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBQuitar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JButton jBValidar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    public static javax.swing.JPanel jPSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTFunActijp;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlEtiqueta;
    private javax.swing.JLabel jlMinimizar;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JPanel jpActivos;
    private javax.swing.JPanel jpFunyActivos;
    public static javax.swing.JTable tablajp;
    // End of variables declaration//GEN-END:variables
}
